### ISSUE TITLE
Add security measures to prevent Guest user see unpublished dialects in Workspaces.

### ISSUE THREAD

**Issue by ksubryan** [First-Peoples-Cultural-Council/nuxeo-addons#10]

**Comment by ksubryan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modify security policies for Guests to ensure that Guests only see Published documents](https://trello.com/c/WXIls3zo/392-modify-security-policies-for-guests-to-ensure-that-guests-only-see-published-documents)

**Comment by pcrossley** [comment]
Hi Kristoff,

Is there any way you can boot me off your GitHub work?

Thanks!

**Comment by ksubryan** [comment]
I am not sure how.
Are you by any chance connecting to nixed-addons?
